"""remove_display_name_from_users

Revision ID: 23cfcafba0a6
Revises: 5516592850dc
Create Date: 2026-06-20 11:39:32.810829

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23cfcafba0a6"
down_revision: Union[str, Sequence[str], None] = "5516592850dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "display_name",
            sa.VARCHAR(length=50),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
